// Code generated by "stringer -type kind"; DO NOT EDIT.

package derrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-1]
	_ = x[NotFound-2]
	_ = x[Unauthorized-3]
	_ = x[Unexpected-4]
	_ = x[NotAllowed-5]
}

const _kind_name = "InvalidNotFoundUnauthorizedUnexpectedNotAllowed"

var _kind_index = [...]uint8{0, 7, 15, 27, 37, 47}

func (i kind) String() string {
	i -= 1
	if i >= kind(len(_kind_index)-1) {
		return "kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _kind_name[_kind_index[i]:_kind_index[i+1]]
}
